export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProductDetailsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
      <h4>Custom Product layout</h4>
    </>
  )
}
