import Link from "next/link"

export const metadata = {
  title: 'Home - Next.js',
  description: 'Generated by home page.',
}

export default function Home() {
  return (
    <>
      <h1>Welcome Home!</h1>
      <Link href='/signup'>Sign Up</Link>
      <br />
      <Link href='/about'>About</Link>
      <br />
      <Link href='/blog'>Blog</Link>
      <br />
      <Link href='/dashboard'>Dashboard</Link>
      <br />
      <Link href='/complex-dashboard'>Complex Dashboard</Link>
      <br />
      <Link href='/docs'>Docs</Link>
      <br />
      <Link href='/products'>Product</Link>
      <br />
      <Link href='/order-product'>Order Product</Link>
      <br />
      <Link href='/profile'>Profile</Link>
    </>
  )
}